version: '3'

services:
  corpus-collector-backend:
    container_name: corpus-collector-backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: local
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - ./.azure-for-docker:/root/.azure
    command:
      - "uvicorn"
      - "app.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--reload"
