apiVersion: v1
kind: Service
metadata:
  name: {{ include "outlook-save-for-training.fullname" . }}
  labels:
    {{- include "outlook-save-for-training.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "outlook-save-for-training.selectorLabels" . | nindent 4 }}
